# Generated by Django 3.2.9 on 2021-12-27 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appname",
                    models.CharField(
                        choices=[
                            ("ACCOUNTS", "Accounts"),
                            ("DRAGONFLY", "Dragonfly"),
                            ("INTELOWL", "Intelowl"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("body", models.TextField()),
                (
                    "read_by_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="To store which users have read a particular notification.",
                        related_name="notifications_read",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
