# Generated by Django 3.2.18 on 2023-02-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certego_saas_notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="appname",
            field=models.CharField(
                choices=[
                    ("ACCOUNTS", "Accounts"),
                    ("DRAGONFLY", "Dragonfly"),
                    ("INTELOWL", "Intelowl"),
                    ("QUOKKA_PUBLIC", "Quokka Public"),
                    ("QUOKKA", "Quokka"),
                ],
                max_length=32,
            ),
        ),
    ]
