repos:
  - repo: https://github.com/myint/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args:
          [
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--ignore-init-module-imports",
            "-i",
          ]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--skip", "venv"]
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: master
#    hooks:
#    -   id: mypy
#        additional_dependencies:
#            - django-stubs
#            - djangorestframework-stubs
#        args: [--no-strict-optional, --ignore-missing-imports]